project:
  type: website

website:
  title: "Pathogen Surveillance"
  favicon: "logo.png"
  search: false
  page-footer: 
    left: |
        [![](logo.png){height=30px}](https://nf-co.re/pathogensurveillance)
    center: |
        [![](usda-logo-color.png){height=30px}](https://www.usda.gov/style-guide/logo) [![](OSU_horizontal_2C_O_over_B.png){height=30px}](https://oregonstate.edu)
  sidebar:
    style: "docked"
    logo: "logo.png"
    tools:
      - icon: twitter
        href: https://twitter.com/phytophthoralab
        text: PhytophthoraLab
      - icon: github
        href: https://github.com/nf-core/pathogensurveillance
        text: Nf-core PathogenSurveillance GitHub

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-depth: 3
    toc-expand: 2
    toc-title: "Contents"
    toc-location: left
    self-contained: true
    embed-resources: true
    grid:
      sidebar-width: 400px
      body-width: 1000px
      margin-width: 0px
      gutter-width: 1.5rem
  pdf:
    toc: true
    documentclass: scrreprt
    prefer-html: true
    
bibliography: references.bib