project:
  type: website

website:
  title: "Pathogen Surveillance"
  favicon: "images/logo.png"
  search: false
  page-footer: 
    left: |
        ![](images/nf-core-logo.png){height=30px} [![](images/logo.png){height=30px}](https://nf-co.re/pathogensurveillance)
    center: |
        [![](images/usda-logo-color.png){height=30px}](https://www.usda.gov/style-guide/logo)  [![](images/OSU_horizontal_2C_O_over_B.png){height=30px}](https://oregonstate.edu)
    right:
      - icon: twitter
        href: https://twitter.com/PhytophthoraLab
        aria-label: PhytophthoraLab
      - icon: github
        href: https://github.com/nf-core/pathogensurveillance
        aria-label: Nf-core PathogenSurveillance GitHub

  sidebar:
    style: "docked"
    logo: "images/logo.png"
    tools:
      - icon: twitter
        href: https://twitter.com/phytophthoralab
        text: PhytophthoraLab
      - icon: github
        href: https://github.com/nf-core/pathogensurveillance
        text: Nf-core PathogenSurveillance GitHub

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-depth: 3
    toc-expand: 2
    toc-title: "Contents"
    toc-location: left
    self-contained: true
    embed-resources: true
    grid:
      sidebar-width: 400px
      body-width: 1000px
      margin-width: 0px
      gutter-width: 1.5rem
  # pdf:
  #   toc: true
  #   documentclass: scrreprt
  #   prefer-html: true
  #   margin-left: 1.5cm
  #   margin-right: 1.5cm
  #   margin-top: 2cm
  #   margin-bottom: 2cm
    
bibliography: references.bib