project:
  type: website

website:
  title: "Pathogen Surveillance Report"
  navbar:
    left:
      - href: index.qmd
        text: Results
      - href: about.qmd
        text: About
    tools:
      - icon: twitter
        href: https://twitter.com/phytophthoralab
        text: PhytophthoraLab
      - icon: github
        href: https://github.com/nf-core/pathogensurveillance
        text: Nf-core PathogenSurveillance GitHub
  sidebar:
    style: "docked"
    search: false
    contents:
      - section: "Results"
        contents:
          - index.qmd
          - identification.qmd
          - diversity.qmd
          - gene_content.qmd
          - map.qmd
      - section: "Analysis Data"
        contents:
          - quality_control.qmd
          - references.qmd
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    embed-resources: true
    
bibliography: references.bib