project:
  type: book

book:
  title: "Pathogensurveillance Report"
  chapters:
    - index.qmd
    - identification.qmd
    - diversity.qmd
    - gene_content.qmd
    - map.qmd
    - quality_control.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: sandstone
  pdf:
    documentclass: scrreprt

params:
    samp_data: "_test_data/metadata_medium.csv"
    ref_data: "_test_data/merged_assembly_stats.tsv"
    snp_phylos: "_test_data/xan_test_22_331_assembly.treefile"
    snp_align: "_test_data/xan_test_22_331_assembly.fasta"
    ani_matrix: "_test_data/comp.csv"
    core_phylo: "_test_data/xan_test.treefile"
    output_dir: "_test_data/output"

