project:
  type: website

website:
  title: "Pathogen Surveillance Report"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: twitter
        href: https://twitter.com/phytophthoralab
        text: PhytophthoraLab
      - icon: github
        href: https://github.com/nf-core/pathogensurveillance
        text: Nf-core PathogenSurveillance GitHub

format:
  html:
    theme: sandstone
    toc: true
    toc-depth: 3
    toc-expand: 2
    toc-title: "Contents"
    toc-location: left
    self-contained: true
    embed-resources: true
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 0px
      gutter-width: 1.5rem
  pdf:
    toc: true
    documentclass: scrreprt
    prefer-html: true
    
bibliography: references.bib