project:
  type: website

website:
  title: "Pathogensurveillance Report"
  navbar:
    left:
      - href: index.qmd
        text: Summary
      - href: identification.qmd
        text: Identity
      - href: diversity.qmd
        text: Diversity
      - href: gene_content.qmd
        text: Genes
      - href: map.qmd
        text: Maps
      - href: quality_control.qmd
        text: Quality Control
      - references.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/phytophthoralab
        text: PhytophthoraLab
      - icon: github
        href: https://github.com/nf-core/pathogensurveillance
        text: Nf-core PathogenSurveillance GitHub

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    
    